import type { RiverItem, OpenTask } from '../features/river/types';

const base = { occurred_at: '2026-10-02T12:00:00Z', time_precision: 'instant' as const, preset_id: null, preview: '预览内容', capabilities: [] };
export const memoItem: RiverItem = { ...base, source_type: 'memo', source_id: '7', preview: '根 Memo #task', target: { type: 'memo', memo_id: 7 }, capabilities: ['read_thread', 'reply', 'edit_tags'], source_specific: { author: 'user', tags: ['task'], reply_count: 2 } };
export const diaryItem: Extract<RiverItem, { source_type: 'diary' }> = { ...base, source_type: 'diary', source_id: '6:2026-10-01', preset_id: 6, time_precision: 'day', preview: '日记预览', target: { type: 'diary', preset_id: 6, day: '2026-10-01' }, capabilities: ['read_full'], source_specific: { day: '2026-10-01' } };
export const heartbeatItem: Extract<RiverItem, { source_type: 'heartbeat' }> = { ...base, source_type: 'heartbeat', source_id: 'ba9486ed-3a85-4a0a-937b-d49a903a70a1', preset_id: 6, preview: '心跳预览', target: { type: 'heartbeat', session_uuid: 'ba9486ed-3a85-4a0a-937b-d49a903a70a1' }, capabilities: ['open_ledger'], source_specific: { launch_source: 'auto', domain: '', status: 'succeeded' } };
export const taskCreated: RiverItem = { ...base, source_type: 'task', source_id: 'created:7', preview: '任务已创建', target: { type: 'task', entry_id: 7 }, source_specific: { event_kind: 'created', title: '同一个任务', entry_type: 'todo', status: 'archived', is_pinned: false, start_date: '2026-10-02', due_date: null, cycle_start: null, cycle_due: null } };
export const taskCompleted: RiverItem = { ...taskCreated, source_id: 'completed:8', preview: '任务已完成', source_specific: { ...taskCreated.source_specific, event_kind: 'completed', completion_id: 8, completion_note: '', completion_cycle_start: null } };
export const chronicleItem: RiverItem = { ...base, source_type: 'chronicle', source_id: '7', preset_id: 6, time_precision: 'day', preview: '历史事件', target: { type: 'chronicle', id: 7 }, capabilities: ['read', 'edit', 'delete'], source_specific: { event_time: '2026-09-15', kind: 'milestone', scope: null, keywords: [] } };
export const allItems = [taskCompleted, diaryItem, memoItem, heartbeatItem, taskCreated, chronicleItem];
export const openTask: OpenTask = { id: 41, title: '来源首项', description: '', entry_type: 'todo', status: 'active', is_pinned: false, start_date: '2026-10-01', tags: [], due_date: null, cycle_due: null, next_periodic_due: null };
export const heartbeatDetail = { session_uuid: heartbeatItem.target.session_uuid, preset_id: 6, preset_name: '测试 Agent', launch_source: 'auto', domain: '', status: 'succeeded', content: '# 最终全文\n\n这不是预览。', started_at: null, completed_at: '2026-10-02T12:00:00Z', seed_message: '不可展示seed', tool_history: ['不可展示tool'], error_summary: '不可展示error', finalization_reason: null, attempt_number: 1, wake_up_task_id: null, source_conversation_id: null, acknowledged_at: null };
export const diaryDetail = { preset_id: 6, day: '2026-10-01', occurred_at: '2026-10-01T01:00:00Z', time_precision: 'day', content: '# 日记全文\n\ncanonical 正文\r\n' };
