/**
 * CP3 Task read models — exact `ScheduleEntrySerializer` / `CompletionRecordSerializer`
 * wire shapes (ReactSheet §3.13 + backend `tasks/serializers.py`).
 *
 * ReactSheet §4.1–4.4 is stale illustrative prose (`type`, `status`, `scheduled_date`,
 * `recurrence`, `priority`, `gcal_event_id`); it is NOT the canonical shape and is not
 * consumed here.
 *
 * All date fields are date-only `YYYY-MM-DD` strings or `null`; they are never passed
 * through `Date`/UTC conversion by the API or payload layers.
 */

export const TASK_TYPES = ['todo', 'periodic', 'goal'] as const;
export type TaskType = (typeof TASK_TYPES)[number];

export const TASK_STATUSES = ['active', 'suspended', 'escalated', 'archived'] as const;
export type TaskStatus = (typeof TASK_STATUSES)[number];

export const TASK_INTERVAL_UNITS = ['day', 'week', 'month'] as const;
export type TaskIntervalUnit = (typeof TASK_INTERVAL_UNITS)[number];

export const TASK_END_TYPES = ['never', 'count', 'date'] as const;
export type TaskEndType = (typeof TASK_END_TYPES)[number];

export const TASK_GOAL_PERIODS = ['week', 'month'] as const;
export type TaskGoalPeriod = (typeof TASK_GOAL_PERIODS)[number];

/** ScheduleEntry as returned by `/api/tasks/entries/` (snake_case wire fields). */
export interface TaskEntry {
  id: number;
  title: string;
  description: string;
  entry_type: TaskType;
  status: TaskStatus;
  is_pinned: boolean;
  start_date: string;
  tags: string[];
  /** todo */
  due_date: string | null;
  /** periodic */
  interval_unit: TaskIntervalUnit | null;
  interval_value: number | null;
  end_type: TaskEndType | null;
  end_count: number | null;
  end_date: string | null;
  occurrences_done: number;
  /** goal */
  goal_count: number | null;
  goal_period: TaskGoalPeriod | null;
  cycle_start: string | null;
  cycle_due: string | null;
  /** GCal link is one-way ExoCore → GCal; "" means unlinked. */
  gcal_event_id: string;
  gcal_event_link: string;
  /** computed */
  current_cycle_completions: number;
  next_periodic_due: string | null;
  created_at: string;
  updated_at: string;
}

/** One check-in row from `CompletionRecordSerializer`; `entry` is the ScheduleEntry pk. */
export interface CompletionRecord {
  id: number;
  entry: number;
  completed_at: string;
  cycle_start: string | null;
  note: string;
}

/** Actual list filters supported by `ScheduleEntryListCreateView.get_queryset`. */
export interface TaskFilters {
  status?: TaskStatus;
  entry_type?: TaskType;
  is_pinned?: boolean;
}

/** POST `/api/tasks/entries/<id>/gcal/` success envelope (HTTP 200). */
export interface GCalPushResult {
  gcal_synced: true;
  gcal_event_id: string;
  gcal_event_link: string;
}

export const CALENDAR_EVENT_SOURCES = ['gcal', 'exocore'] as const;
export type CalendarEventSource = (typeof CALENDAR_EVENT_SOURCES)[number];

export type CalendarSnapshotKind = 'calendar' | 'today';

/**
 * Merged snapshot event as written by `scheduler/calendar_sync.py`:
 * `_fetch_gcal_events` rows carry `calendar_name`/`calendar_id`; ExoCore rows carry
 * `exocore_entry_id` and a real `entry_type`/`status`. `start`/`end` may be date-only
 * (all-day) or an ISO datetime string — the snapshot is already local/offset-rendered
 * by the backend generator and must not be UTC-normalized here.
 */
export interface CalendarEvent {
  id: string;
  source: CalendarEventSource;
  title: string;
  start: string;
  end: string;
  all_day: boolean;
  description: string;
  location: string | null;
  html_link: string | null;
  entry_type: TaskType | null;
  status: TaskStatus | null;
  /** Present iff source === 'exocore'; the same entry opened by the Task detail. */
  exocore_entry_id: number | null;
  calendar_name: string | null;
  calendar_id: string | null;
}

/** `{fetched_at, window_start, window_end, count, events}` — generated by the 07/14/21 job. */
export interface CalendarSnapshot {
  fetched_at: string;
  window_start: string;
  window_end: string;
  count: number;
  events: CalendarEvent[];
}
